[package]
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-net-shaper"
description = "The safecoin cluster network shaping tool"
version = "1.6.13"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
clap = "2.33.1"
serde = "1.0.122"
serde_json = "1.0.56"
solana-clap-utils = { path = "../clap-utils", version = "=1.6.13" }
solana-logger = { path = "../logger", version = "=1.6.13" }
rand = "0.7.0"

[[bin]]
name = "safecoin-net-shaper"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
