[package]
name = "safecoin-keygen"
version = "1.6.13"
description = "Safecoin key generation utility"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/safecoin-keygen"
edition = "2018"

[dependencies]
bs58 = "0.3.1"
clap = "2.33"
dirs-next = "2.0.0"
num_cpus = "1.13.0"
solana-clap-utils = { path = "../clap-utils", version = "=1.6.13" }
solana-cli-config = { path = "../cli-config", version = "=1.6.13" }
solana-remote-wallet = { path = "../remote-wallet", version = "=1.6.13" }
solana-sdk = { path = "../sdk", version = "=1.6.13" }
solana-version = { path = "../version", version = "=1.6.13" }
tiny-bip39 = "0.7.0"

[[bin]]
name = "safecoin-keygen"
path = "src/keygen.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
