[package]
name = "solana-failure-program"
version = "1.6.13"
description = "Safecoin failure program"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-failure-program"
edition = "2018"

[dependencies]
solana-sdk = { path = "../../sdk", version = "=1.6.13" }

[dev-dependencies]
solana-runtime = { path = "../../runtime", version = "=1.6.13" }

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_failure_program"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
