[package]
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
description = "I will find you and I will stake you"
edition = "2018"
homepage = "https://solana.com/"
documentation = "https://docs.rs/"
license = "Apache-2.0"
name = "safecoin-stake-o-matic"
repository = "https://github.com/solana-labs/stake-o-matic"
version = "1.6.13"

[dependencies]
clap = "2.33.0"
log = "0.4.11"
reqwest = { version = "0.11.2", default-features = false, features = ["blocking", "rustls-tls", "json"] }
semver = "0.9.0"
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0.62"
serde_yaml = "0.8.13"
solana-clap-utils = { path = "../clap-utils", version = "=1.6.13" }
solana-client = { path = "../client", version = "=1.6.13" }
solana-cli-config = { path = "../cli-config", version = "=1.6.13" }
solana-cli-output = { path = "../cli-output", version = "=1.6.13" }
solana-logger = { path = "../logger", version = "=1.6.13" }
solana-metrics = { path = "../metrics", version = "=1.6.13" }
solana-notifier = { path = "../notifier", version = "=1.6.13" }
solana-sdk = { path = "../sdk", version = "=1.6.13" }
solana-stake-program = { path = "../programs/stake", version = "=1.6.13" }
solana-transaction-status = { path = "../transaction-status", version = "=1.6.13" }
thiserror = "1.0.21"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
